In [ ]:
from sklearn.linear_model import LogisticRegression as LR 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier as RFC
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits 
digits = load_digits() #<--- Handwriiten digits dataset

In [ ]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(digits.data,digits.target,test_size = 0.2)

In [ ]:
model_LR = LR()
model_LR.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
model_LR.score(x_test,y_test) #<-- accuracy using logistic regression

0.9611111111111111

In [ ]:
model_svm = SVC()
model_svm.fit(x_train,y_train)

SVC()

In [ ]:
model_svm.score(x_test,y_test)

0.9916666666666667

In [ ]:
model_rfs = RFC()
model_rfs.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
model_rfs.score(x_test,y_test)

0.9833333333333333

In [ ]:
#k-fold method is the best method to check the accuracy of model
from sklearn.model_selection import KFold
kf = KFold(n_splits = 4) #n_splits we will tell how many folds to create in dataset
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
#how it works 
for train_index, test_index in kf.split(np.arange(1,11)):
  print(train_index,test_index)

[3 4 5 6 7 8 9] [0 1 2]
[0 1 2 6 7 8 9] [3 4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [ ]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [ ]:
#stratifiedKFold(uniform) is better than KFold(non-uniform)
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits = 3)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    #solver='liblinear',multi_class='ovr' <- u can pass in logistic regression
    #gamma='auto' <-an SVC argument
    scores_logistic.append(get_score(LR(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RFC(), X_train, X_test, y_train, y_test))


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

In [ ]:
print(scores_logistic)
print(scores_svm)
print(scores_rf)

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]
[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]
[0.9282136894824707, 0.9515859766277128, 0.9265442404006677]


In [ ]:
from sklearn.model_selection import cross_val_score as cvs 
cvs(LR(),digits.data,digits.target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cvs(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cvs(RFC(),digits.data,digits.target)

array([0.93611111, 0.91666667, 0.96100279, 0.96935933, 0.93036212])